from .user import User
from .patient import Patient
from .doctor import Doctor
from .staff import Staff
from .appointment import Appointment
from .prescription import Prescription
from .lab_report import LabReport
from .medicine_reminder import MedicineReminder
from .chat_history import ChatHistory
from .hospital_document import HospitalDocument
from .prescription_scan import PrescriptionScan
from .disease_prediction import DiseasePrediction